{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "cdd4588f",
   "metadata": {},
   "source": [
    "1. Import dataset\n",
    "2. Eksplorasi data\n",
    "3. Preprocess data\n",
    "4. Modeling\n",
    "5. Evaluasi\n",
    "6. Saving model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "id": "eebcc848",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>NO</th>\n",
       "      <th>TANGGAL PEMBAYARAN</th>\n",
       "      <th>JATUH TEMPO PAJAK</th>\n",
       "      <th>DURASI</th>\n",
       "      <th>JENIS KELAMIN</th>\n",
       "      <th>PBB TERHUTANG</th>\n",
       "      <th>DENDA</th>\n",
       "      <th>LABEL</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1</td>\n",
       "      <td>1/1/2023</td>\n",
       "      <td>11/9/2023</td>\n",
       "      <td>253</td>\n",
       "      <td>L</td>\n",
       "      <td>799440</td>\n",
       "      <td>0</td>\n",
       "      <td>PATUH</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2</td>\n",
       "      <td>5/1/2023</td>\n",
       "      <td>11/9/2023</td>\n",
       "      <td>249</td>\n",
       "      <td>L</td>\n",
       "      <td>401250</td>\n",
       "      <td>0</td>\n",
       "      <td>PATUH</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>3</td>\n",
       "      <td>10/1/2023</td>\n",
       "      <td>11/9/2023</td>\n",
       "      <td>244</td>\n",
       "      <td>L</td>\n",
       "      <td>799440</td>\n",
       "      <td>0</td>\n",
       "      <td>PATUH</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>4</td>\n",
       "      <td>15/01/2023</td>\n",
       "      <td>11/9/2023</td>\n",
       "      <td>239</td>\n",
       "      <td>L</td>\n",
       "      <td>443816</td>\n",
       "      <td>0</td>\n",
       "      <td>PATUH</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>5</td>\n",
       "      <td>20/10/2023</td>\n",
       "      <td>11/9/2023</td>\n",
       "      <td>39</td>\n",
       "      <td>L</td>\n",
       "      <td>258300</td>\n",
       "      <td>40562</td>\n",
       "      <td>TIDAK PATUH</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>354</th>\n",
       "      <td>494</td>\n",
       "      <td>16/11/2023</td>\n",
       "      <td>11/9/2023</td>\n",
       "      <td>66</td>\n",
       "      <td>P</td>\n",
       "      <td>117975</td>\n",
       "      <td>18876</td>\n",
       "      <td>TIDAK PATUH</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>355</th>\n",
       "      <td>495</td>\n",
       "      <td>11/10/2023</td>\n",
       "      <td>11/9/2023</td>\n",
       "      <td>30</td>\n",
       "      <td>P</td>\n",
       "      <td>314290</td>\n",
       "      <td>50287</td>\n",
       "      <td>TIDAK PATUH</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>356</th>\n",
       "      <td>496</td>\n",
       "      <td>3/10/2023</td>\n",
       "      <td>11/9/2023</td>\n",
       "      <td>22</td>\n",
       "      <td>P</td>\n",
       "      <td>851780</td>\n",
       "      <td>136285</td>\n",
       "      <td>TIDAK PATUH</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>357</th>\n",
       "      <td>497</td>\n",
       "      <td>29/07/2023</td>\n",
       "      <td>11/9/2023</td>\n",
       "      <td>44</td>\n",
       "      <td>P</td>\n",
       "      <td>830100</td>\n",
       "      <td>0</td>\n",
       "      <td>PATUH</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>358</th>\n",
       "      <td>499</td>\n",
       "      <td>6/8/2023</td>\n",
       "      <td>11/9/2023</td>\n",
       "      <td>36</td>\n",
       "      <td>P</td>\n",
       "      <td>435380</td>\n",
       "      <td>0</td>\n",
       "      <td>PATUH</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>359 rows × 8 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "      NO TANGGAL PEMBAYARAN JATUH TEMPO PAJAK  DURASI JENIS KELAMIN  \\\n",
       "0      1           1/1/2023         11/9/2023     253             L   \n",
       "1      2           5/1/2023         11/9/2023     249             L   \n",
       "2      3          10/1/2023         11/9/2023     244             L   \n",
       "3      4         15/01/2023         11/9/2023     239             L   \n",
       "4      5         20/10/2023         11/9/2023      39             L   \n",
       "..   ...                ...               ...     ...           ...   \n",
       "354  494         16/11/2023         11/9/2023      66             P   \n",
       "355  495         11/10/2023         11/9/2023      30             P   \n",
       "356  496          3/10/2023         11/9/2023      22             P   \n",
       "357  497         29/07/2023         11/9/2023      44             P   \n",
       "358  499           6/8/2023         11/9/2023      36             P   \n",
       "\n",
       "     PBB TERHUTANG   DENDA        LABEL  \n",
       "0           799440       0        PATUH  \n",
       "1           401250       0        PATUH  \n",
       "2           799440       0        PATUH  \n",
       "3           443816       0        PATUH  \n",
       "4           258300   40562  TIDAK PATUH  \n",
       "..             ...     ...          ...  \n",
       "354         117975   18876  TIDAK PATUH  \n",
       "355         314290   50287  TIDAK PATUH  \n",
       "356         851780  136285  TIDAK PATUH  \n",
       "357         830100       0        PATUH  \n",
       "358         435380       0        PATUH  \n",
       "\n",
       "[359 rows x 8 columns]"
      ]
     },
     "execution_count": 29,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "## Import dataset\n",
    "import pandas as pd\n",
    "\n",
    "df = pd.read_csv(\"dataset_pbb.csv\")\n",
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "id": "627374f9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'pandas.core.frame.DataFrame'>\n",
      "RangeIndex: 359 entries, 0 to 358\n",
      "Data columns (total 8 columns):\n",
      " #   Column              Non-Null Count  Dtype \n",
      "---  ------              --------------  ----- \n",
      " 0   NO                  359 non-null    int64 \n",
      " 1   TANGGAL PEMBAYARAN  359 non-null    object\n",
      " 2   JATUH TEMPO PAJAK   359 non-null    object\n",
      " 3   DURASI              359 non-null    int64 \n",
      " 4   JENIS KELAMIN       359 non-null    object\n",
      " 5   PBB TERHUTANG       359 non-null    int64 \n",
      " 6   DENDA               359 non-null    int64 \n",
      " 7   LABEL               359 non-null    object\n",
      "dtypes: int64(4), object(4)\n",
      "memory usage: 22.6+ KB\n"
     ]
    }
   ],
   "source": [
    "## cek dataset\n",
    "df.info()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "2f10ad22",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>NO</th>\n",
       "      <th>TANGGAL PEMBAYARAN</th>\n",
       "      <th>JATUH TEMPO PAJAK</th>\n",
       "      <th>DURASI</th>\n",
       "      <th>JENIS KELAMIN</th>\n",
       "      <th>PBB TERHUTANG</th>\n",
       "      <th>DENDA</th>\n",
       "      <th>LABEL</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1.0</td>\n",
       "      <td>1/1/2023</td>\n",
       "      <td>11/9/2023</td>\n",
       "      <td>253.0</td>\n",
       "      <td>L</td>\n",
       "      <td>799,440</td>\n",
       "      <td>0</td>\n",
       "      <td>PATUH</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2.0</td>\n",
       "      <td>5/1/2023</td>\n",
       "      <td>11/9/2023</td>\n",
       "      <td>249.0</td>\n",
       "      <td>L</td>\n",
       "      <td>401,250</td>\n",
       "      <td>0</td>\n",
       "      <td>PATUH</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>3.0</td>\n",
       "      <td>10/1/2023</td>\n",
       "      <td>11/9/2023</td>\n",
       "      <td>244.0</td>\n",
       "      <td>L</td>\n",
       "      <td>799,440</td>\n",
       "      <td>0</td>\n",
       "      <td>PATUH</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>4.0</td>\n",
       "      <td>15/01/2023</td>\n",
       "      <td>11/9/2023</td>\n",
       "      <td>239.0</td>\n",
       "      <td>L</td>\n",
       "      <td>443,816</td>\n",
       "      <td>0</td>\n",
       "      <td>PATUH</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>5.0</td>\n",
       "      <td>20/10/2023</td>\n",
       "      <td>11/9/2023</td>\n",
       "      <td>39.0</td>\n",
       "      <td>L</td>\n",
       "      <td>258,300</td>\n",
       "      <td>40,562</td>\n",
       "      <td>TIDAK PATUH</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>494</th>\n",
       "      <td>495.0</td>\n",
       "      <td>11/10/2023</td>\n",
       "      <td>11/9/2023</td>\n",
       "      <td>30.0</td>\n",
       "      <td>P</td>\n",
       "      <td>314,290</td>\n",
       "      <td>50,287</td>\n",
       "      <td>TIDAK PATUH</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>495</th>\n",
       "      <td>496.0</td>\n",
       "      <td>3/10/2023</td>\n",
       "      <td>11/9/2023</td>\n",
       "      <td>22.0</td>\n",
       "      <td>P</td>\n",
       "      <td>851,780</td>\n",
       "      <td>136,285</td>\n",
       "      <td>TIDAK PATUH</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>496</th>\n",
       "      <td>497.0</td>\n",
       "      <td>29/07/2023</td>\n",
       "      <td>11/9/2023</td>\n",
       "      <td>44.0</td>\n",
       "      <td>P</td>\n",
       "      <td>830,100</td>\n",
       "      <td>0</td>\n",
       "      <td>PATUH</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>497</th>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>498</th>\n",
       "      <td>499.0</td>\n",
       "      <td>6/8/2023</td>\n",
       "      <td>11/9/2023</td>\n",
       "      <td>36.0</td>\n",
       "      <td>P</td>\n",
       "      <td>435,380</td>\n",
       "      <td>0</td>\n",
       "      <td>PATUH</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>499 rows × 8 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "        NO TANGGAL PEMBAYARAN JATUH TEMPO PAJAK  DURASI JENIS KELAMIN  \\\n",
       "0      1.0           1/1/2023         11/9/2023   253.0             L   \n",
       "1      2.0           5/1/2023         11/9/2023   249.0             L   \n",
       "2      3.0          10/1/2023         11/9/2023   244.0             L   \n",
       "3      4.0         15/01/2023         11/9/2023   239.0             L   \n",
       "4      5.0         20/10/2023         11/9/2023    39.0             L   \n",
       "..     ...                ...               ...     ...           ...   \n",
       "494  495.0         11/10/2023         11/9/2023    30.0             P   \n",
       "495  496.0          3/10/2023         11/9/2023    22.0             P   \n",
       "496  497.0         29/07/2023         11/9/2023    44.0             P   \n",
       "497    NaN                NaN               NaN     NaN           NaN   \n",
       "498  499.0           6/8/2023         11/9/2023    36.0             P   \n",
       "\n",
       "    PBB TERHUTANG    DENDA        LABEL  \n",
       "0         799,440        0        PATUH  \n",
       "1         401,250        0        PATUH  \n",
       "2         799,440        0        PATUH  \n",
       "3         443,816        0        PATUH  \n",
       "4         258,300   40,562  TIDAK PATUH  \n",
       "..            ...      ...          ...  \n",
       "494       314,290   50,287  TIDAK PATUH  \n",
       "495       851,780  136,285  TIDAK PATUH  \n",
       "496       830,100        0        PATUH  \n",
       "497           NaN      NaN          NaN  \n",
       "498       435,380        0        PATUH  \n",
       "\n",
       "[499 rows x 8 columns]"
      ]
     },
     "execution_count": 11,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# df.dropna()\n",
    "# df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "id": "400d2d24",
   "metadata": {},
   "outputs": [],
   "source": [
    "## Fitur\n",
    "drop_column = [\"NO\", \"LABEL\", \"TANGGAL PEMBAYARAN\", \"JATUH TEMPO PAJAK\"]\n",
    "X = df.drop(drop_column, axis=1)\n",
    "\n",
    "## Label\n",
    "y = df[\"LABEL\"]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 32,
   "id": "6d540bac",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>DURASI</th>\n",
       "      <th>JENIS KELAMIN</th>\n",
       "      <th>PBB TERHUTANG</th>\n",
       "      <th>DENDA</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>253</td>\n",
       "      <td>L</td>\n",
       "      <td>799440</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>249</td>\n",
       "      <td>L</td>\n",
       "      <td>401250</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>244</td>\n",
       "      <td>L</td>\n",
       "      <td>799440</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>239</td>\n",
       "      <td>L</td>\n",
       "      <td>443816</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>39</td>\n",
       "      <td>L</td>\n",
       "      <td>258300</td>\n",
       "      <td>40562</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>354</th>\n",
       "      <td>66</td>\n",
       "      <td>P</td>\n",
       "      <td>117975</td>\n",
       "      <td>18876</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>355</th>\n",
       "      <td>30</td>\n",
       "      <td>P</td>\n",
       "      <td>314290</td>\n",
       "      <td>50287</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>356</th>\n",
       "      <td>22</td>\n",
       "      <td>P</td>\n",
       "      <td>851780</td>\n",
       "      <td>136285</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>357</th>\n",
       "      <td>44</td>\n",
       "      <td>P</td>\n",
       "      <td>830100</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>358</th>\n",
       "      <td>36</td>\n",
       "      <td>P</td>\n",
       "      <td>435380</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>359 rows × 4 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "     DURASI JENIS KELAMIN  PBB TERHUTANG   DENDA\n",
       "0       253             L         799440       0\n",
       "1       249             L         401250       0\n",
       "2       244             L         799440       0\n",
       "3       239             L         443816       0\n",
       "4        39             L         258300   40562\n",
       "..      ...           ...            ...     ...\n",
       "354      66             P         117975   18876\n",
       "355      30             P         314290   50287\n",
       "356      22             P         851780  136285\n",
       "357      44             P         830100       0\n",
       "358      36             P         435380       0\n",
       "\n",
       "[359 rows x 4 columns]"
      ]
     },
     "execution_count": 32,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "X"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 33,
   "id": "8455db3b",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "0            PATUH\n",
       "1            PATUH\n",
       "2            PATUH\n",
       "3            PATUH\n",
       "4      TIDAK PATUH\n",
       "          ...     \n",
       "354    TIDAK PATUH\n",
       "355    TIDAK PATUH\n",
       "356    TIDAK PATUH\n",
       "357          PATUH\n",
       "358          PATUH\n",
       "Name: LABEL, Length: 359, dtype: object"
      ]
     },
     "execution_count": 33,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "y"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "79f65914",
   "metadata": {},
   "outputs": [],
   "source": [
    "# grafik\n",
    "import matplotlib.pyplot as plt\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 34,
   "id": "2568c26c",
   "metadata": {},
   "outputs": [],
   "source": [
    "## train test split\n",
    "from sklearn.model_selection import train_test_split\n",
    "X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.7)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 35,
   "id": "725641b6",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>DURASI</th>\n",
       "      <th>JENIS KELAMIN</th>\n",
       "      <th>PBB TERHUTANG</th>\n",
       "      <th>DENDA</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>148</th>\n",
       "      <td>81</td>\n",
       "      <td>P</td>\n",
       "      <td>318087</td>\n",
       "      <td>50894</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>239</th>\n",
       "      <td>66</td>\n",
       "      <td>P</td>\n",
       "      <td>323025</td>\n",
       "      <td>51684</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>134</th>\n",
       "      <td>67</td>\n",
       "      <td>L</td>\n",
       "      <td>477791</td>\n",
       "      <td>76447</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>196</th>\n",
       "      <td>67</td>\n",
       "      <td>P</td>\n",
       "      <td>769080</td>\n",
       "      <td>123053</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>113</th>\n",
       "      <td>91</td>\n",
       "      <td>L</td>\n",
       "      <td>464320</td>\n",
       "      <td>74292</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>215</th>\n",
       "      <td>157</td>\n",
       "      <td>P</td>\n",
       "      <td>127400</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>72</th>\n",
       "      <td>105</td>\n",
       "      <td>L</td>\n",
       "      <td>348160</td>\n",
       "      <td>55706</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>81</th>\n",
       "      <td>62</td>\n",
       "      <td>L</td>\n",
       "      <td>160805</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>225</th>\n",
       "      <td>81</td>\n",
       "      <td>P</td>\n",
       "      <td>323025</td>\n",
       "      <td>51684</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>266</th>\n",
       "      <td>67</td>\n",
       "      <td>P</td>\n",
       "      <td>493360</td>\n",
       "      <td>78938</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>251 rows × 4 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "     DURASI JENIS KELAMIN  PBB TERHUTANG   DENDA\n",
       "148      81             P         318087   50894\n",
       "239      66             P         323025   51684\n",
       "134      67             L         477791   76447\n",
       "196      67             P         769080  123053\n",
       "113      91             L         464320   74292\n",
       "..      ...           ...            ...     ...\n",
       "215     157             P         127400       0\n",
       "72      105             L         348160   55706\n",
       "81       62             L         160805       0\n",
       "225      81             P         323025   51684\n",
       "266      67             P         493360   78938\n",
       "\n",
       "[251 rows x 4 columns]"
      ]
     },
     "execution_count": 35,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "X_train"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 36,
   "id": "d4981ab5",
   "metadata": {},
   "outputs": [],
   "source": [
    "## preprocessing data\n",
    "## convert categorical -> numerical\n",
    "categorical_columns = [\"JENIS KELAMIN\"]\n",
    "X_train_encoded = pd.get_dummies(X_train, columns=categorical_columns)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 37,
   "id": "87e40f63",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>DURASI</th>\n",
       "      <th>PBB TERHUTANG</th>\n",
       "      <th>DENDA</th>\n",
       "      <th>JENIS KELAMIN_L</th>\n",
       "      <th>JENIS KELAMIN_P</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>148</th>\n",
       "      <td>81</td>\n",
       "      <td>318087</td>\n",
       "      <td>50894</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>239</th>\n",
       "      <td>66</td>\n",
       "      <td>323025</td>\n",
       "      <td>51684</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>134</th>\n",
       "      <td>67</td>\n",
       "      <td>477791</td>\n",
       "      <td>76447</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>196</th>\n",
       "      <td>67</td>\n",
       "      <td>769080</td>\n",
       "      <td>123053</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>113</th>\n",
       "      <td>91</td>\n",
       "      <td>464320</td>\n",
       "      <td>74292</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>215</th>\n",
       "      <td>157</td>\n",
       "      <td>127400</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>72</th>\n",
       "      <td>105</td>\n",
       "      <td>348160</td>\n",
       "      <td>55706</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>81</th>\n",
       "      <td>62</td>\n",
       "      <td>160805</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>225</th>\n",
       "      <td>81</td>\n",
       "      <td>323025</td>\n",
       "      <td>51684</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>266</th>\n",
       "      <td>67</td>\n",
       "      <td>493360</td>\n",
       "      <td>78938</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>251 rows × 5 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "     DURASI  PBB TERHUTANG   DENDA  JENIS KELAMIN_L  JENIS KELAMIN_P\n",
       "148      81         318087   50894                0                1\n",
       "239      66         323025   51684                0                1\n",
       "134      67         477791   76447                1                0\n",
       "196      67         769080  123053                0                1\n",
       "113      91         464320   74292                1                0\n",
       "..      ...            ...     ...              ...              ...\n",
       "215     157         127400       0                0                1\n",
       "72      105         348160   55706                1                0\n",
       "81       62         160805       0                1                0\n",
       "225      81         323025   51684                0                1\n",
       "266      67         493360   78938                0                1\n",
       "\n",
       "[251 rows x 5 columns]"
      ]
     },
     "execution_count": 37,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "X_train_encoded"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 38,
   "id": "4a170ea0",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>DURASI</th>\n",
       "      <th>PBB TERHUTANG</th>\n",
       "      <th>DENDA</th>\n",
       "      <th>JENIS KELAMIN_L</th>\n",
       "      <th>JENIS KELAMIN_P</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>128</th>\n",
       "      <td>75</td>\n",
       "      <td>320727</td>\n",
       "      <td>51317</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>36</th>\n",
       "      <td>219</td>\n",
       "      <td>146480</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>283</th>\n",
       "      <td>91</td>\n",
       "      <td>798120</td>\n",
       "      <td>127700</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>159</th>\n",
       "      <td>65</td>\n",
       "      <td>351510</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>201</th>\n",
       "      <td>30</td>\n",
       "      <td>464320</td>\n",
       "      <td>74292</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>163</th>\n",
       "      <td>36</td>\n",
       "      <td>94230</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>68</th>\n",
       "      <td>73</td>\n",
       "      <td>495940</td>\n",
       "      <td>79351</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>66</th>\n",
       "      <td>30</td>\n",
       "      <td>371400</td>\n",
       "      <td>59424</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>206</th>\n",
       "      <td>93</td>\n",
       "      <td>930600</td>\n",
       "      <td>148896</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>151</th>\n",
       "      <td>44</td>\n",
       "      <td>239500</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>108 rows × 5 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "     DURASI  PBB TERHUTANG   DENDA  JENIS KELAMIN_L  JENIS KELAMIN_P\n",
       "128      75         320727   51317                1                0\n",
       "36      219         146480       0                1                0\n",
       "283      91         798120  127700                0                1\n",
       "159      65         351510       0                0                1\n",
       "201      30         464320   74292                0                1\n",
       "..      ...            ...     ...              ...              ...\n",
       "163      36          94230       0                0                1\n",
       "68       73         495940   79351                1                0\n",
       "66       30         371400   59424                1                0\n",
       "206      93         930600  148896                0                1\n",
       "151      44         239500       0                0                1\n",
       "\n",
       "[108 rows x 5 columns]"
      ]
     },
     "execution_count": 38,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "X_test_encoded = pd.get_dummies(X_test, columns=categorical_columns)\n",
    "X_test_encoded"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 39,
   "id": "8d9bab11",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,\n",
       "       0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1,\n",
       "       1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1,\n",
       "       1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,\n",
       "       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,\n",
       "       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1,\n",
       "       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,\n",
       "       0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0,\n",
       "       1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0,\n",
       "       0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,\n",
       "       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,\n",
       "       1, 1, 1, 1, 0, 1, 0, 1, 1])"
      ]
     },
     "execution_count": 39,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "## Label\n",
    "from sklearn.preprocessing import LabelEncoder\n",
    "import numpy as np\n",
    "\n",
    "y_train_1d = np.ravel(y_train)\n",
    "lb = LabelEncoder()\n",
    "y_train_encoded = lb.fit_transform(y_train_1d)\n",
    "y_train_encoded"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 40,
   "id": "022ca355",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0,\n",
       "       1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,\n",
       "       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0,\n",
       "       0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,\n",
       "       1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0])"
      ]
     },
     "execution_count": 40,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "y_test_1d = np.ravel(y_test)\n",
    "y_test_encoded = lb.fit_transform(y_test_1d)\n",
    "y_test_encoded"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 41,
   "id": "52b47868",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Akurasi dengan menggunakan Logistic Regression:  1.0\n"
     ]
    }
   ],
   "source": [
    "## model logistic regression\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn import metrics\n",
    "\n",
    "lr = LogisticRegression()\n",
    "\n",
    "lr.fit(X_train_encoded, y_train_encoded) #melakukan training\n",
    "\n",
    "### evaluasi\n",
    "y_pred = lr.predict(X_test_encoded)  #melakukan testing\n",
    "score_lr = metrics.accuracy_score(y_test_encoded, y_pred)  #mengukur evaluasi / akurasi\n",
    "print(\"Akurasi dengan menggunakan Logistic Regression: \", score_lr)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 43,
   "id": "7da32d2f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Akurasi dengan menggunakan Support Vector Machine:  0.5833333333333334\n"
     ]
    }
   ],
   "source": [
    "# model svm\n",
    "from sklearn.svm import SVC\n",
    "from sklearn import metrics\n",
    "\n",
    "svm = SVC(\n",
    "  kernel = 'rbf',\n",
    "  C = 1,\n",
    "  gamma = 0.01\n",
    ")\n",
    "\n",
    "# training\n",
    "svm.fit(X_train_encoded, y_train_encoded)\n",
    "\n",
    "# evaluation\n",
    "y_pred = svm.predict(X_test_encoded)\n",
    "score_svm = metrics.accuracy_score(y_test_encoded, y_pred)\n",
    "print(\"Akurasi dengan menggunakan Support Vector Machine: \", score_svm)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 45,
   "id": "d2b151d9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Akurasi dengan menggunakan Support Vector Machine Polynomial Kernel:  0.9814814814814815\n"
     ]
    }
   ],
   "source": [
    "svmPoly = SVC(\n",
    "  kernel = 'poly',\n",
    "  C = 1,\n",
    "  gamma = 0.01,\n",
    "  degree = 2\n",
    ")\n",
    "\n",
    "svmPoly.fit(X_train_encoded, y_train_encoded)\n",
    "y_pred = svmPoly.predict(X_test_encoded)\n",
    "score_svmP = metrics.accuracy_score(y_test_encoded, y_pred)\n",
    "print(\"Akurasi dengan menggunakan Support Vector Machine Polynomial Kernel: \", score_svmP)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5c466a0c",
   "metadata": {},
   "outputs": [],
   "source": [
    "# confusion matrix"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 47,
   "id": "1a753c41",
   "metadata": {},
   "outputs": [],
   "source": [
    "## save model\n",
    "import pickle\n",
    "\n",
    "with open('model_logistic.pkl', 'wb') as f:\n",
    "    pickle.dump(lr, f)\n",
    "    \n",
    "with open('model_svm.pkl', 'wb') as f:\n",
    "    pickle.dump(svm, f)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b63b07a4",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
